@startmindmap
skinparam topurl StructureDefinition-

* [[logImagingReportCz.html Zpráva ze zobrazovacích metod]]
** [[logHeaderImagingReportCz.html Hlavička dokumentu]]
** [[logBodyImagingReportCz.html Tělo dokumentu]]
** Vizuální podoba dokumentu
** Přílohy
'** Link to Related Report
'** Media
'** Dicom Metadata
@endmindmap