@startmindmap
skinparam topurl StructureDefinition-

* [[logHeaderImagingReportCz.html Hlavička dokumentu]]
** [[logSubjectCz.html Identifikace pacienta]]
/'    Shell we keep or not?
** Preferred Health Professional
'/
** [[logPayerCz.html Zdravotní pojištění]]
/' ***_ Health insurance code
***_ Health insurance name
***_ Health insurance number '/
** [[logIntendedRecipientCz.html Příjemce dokumentu]]
** [[logAttesterCz.html Ověřil]]
***_ Ověřovatel
***_ Datum a čas ověření
** [[logAuthorCz.html Autor dokumentu]]
***_ Autor
***_ Datum a čas uložení
** [[logLegalAuthenticatorCz.html Zodpovídá]]
***_ Zodpovědná osoba
***_ Datum a čas autorizace
** [[logDocumentMetadataCz.html Metadata dokumentu]]
***_ ID dokumentu
***_ Kategorie dokumentu
***_ Stav dokumentu
'***_ Period
***_ Datum a čas vytvoření
***_ Název dokumentu
'***_ Event type
'***_ Specialty
***_ Správce dokumentu
'***_ Document format
***_ Důvěrnost dokumentu
***_ Jazyk dokumentu
***_ Verze
***_ Digitální podpis
'***_ Study Instance UID
'***_ Accession number
@endmindmap