@startmindmap
skinparam topurl StructureDefinition-

* [[ImagingReportCz.html Zpráva ze zobrazovacích metod]]
** [[HeaderImagingReportCz.html Hlavička dokumentu]]
** [[BodyImagingReportCz.html Tělo dokumentu]
'** Link to Related Report
'** Media
'** Dicom Metadata
@endmindmap