@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend

class "Presented Form" <<LogicalModel>> [[StructureDefinition-PresentedFormCz.html]]
note top #EEEEAE [[ConceptMap-AttachmentImagingReport2FHIR-cz.html]]
Concept Map
endnote

class "Attachments" <<LogicalModel>> [[StructureDefinition-AttachmentsCz.html]]
note top #EEEEAE [[ConceptMap-AttachmentImagingReport2FHIR-cz.html]]
Concept Map
endnote

class "cz-diagnosticReport.presentedForm" <<Profile>> [[https://build.fhir.org/ig/HL7-cz/img/StructureDefinition-cz-composition-imaging.html#acc]]
class "cz-attachment" <<Profile>> [[https://hl7.cz/fhir/core/StructureDefinition-cz-attachment.html]]

"Presented Form" -- "Attachments"
"Presented Form" <|. "cz-diagnosticReport.presentedForm"
"Attachments" <|. "cz-attachment"

"Presented Form" -r[hidden]-> "Attachments"
"Presented Form" -d[hidden]-> "cz-diagnosticReport.presentedForm"
"Attachments" -d[hidden]-> "cz-attachment"

@enduml
