@startuml
"Tvůrce zprávy ze zobrazovacích metod" as creator
"Uložiště zprávy ze zobrazovacích metod" as repos
"Spotřebitel zprávy ze zobrazovacích metod" as consumer
"Vytvoření zprávy ze zobrazovacích metod" as (create)
"Použití zprávy ze zobrazovacích metod" as (use)

"Uzavření/uložení zprávy" as (save)
"Vyhledání/Získání zprávy" as (receive)

creator --> (create)
creator --> (save)
consumer --> (use)
consumer --> (receive)
repos --> (save)
repos --> (receive)
@enduml