@startmindmap
skinparam topurl StructureDefinition-

* [[logImagingReportCz.html Zpráva z obrazového vyšetření]]
** [[logHeaderImagingReportCz.html Hlavička dokumentu]]
** [[logBodyImagingReportCz.html Tělo dokumentu]]
** Vizuální podoba dokumentu
** Přílohy
'** Comparison Study
'** Media
'** Dicom Metadata
@endmindmap