@startmindmap
skinparam topurl StructureDefinition-

* [[ImagingReportCz.html Imaging Report]]
** [[HeaderImagingReportCz.html Imaging Report Header]]
** [[BodyImagingReportCz.html Imaging Report Body]]
** Presented Form
** Attachments
'** Comparison Study
'** Media
'** Dicom Metadata
@endmindmap