Profile: CZ_AttachmentObligationsImg
Parent: CZ_AttachmentImg
Id: cz-attachment-obl-img
Title:    "Attachment: Obligations"
Description: "This profile defines obligations for a attachment in FHIR for the purpose of this guide."

* height insert OblCreator(#SHOULD:populate-if-known,L2)
* width insert OblCreator(#SHOULD:populate-if-known,L2)
* frames insert OblCreator(#SHOULD:populate-if-known,L2)
* duration insert OblCreator(#SHOULD:populate-if-known,L2)
* bodySite insert OblCreator(#SHOULD:populate-if-known,L2)
* content.contentType insert OblCreator(#SHOULD:able-to-populate,L2)
* content.language insert OblCreator(#SHOULD:able-to-populate,L2)
* content.data insert OblCreator(#SHOULD:able-to-populate,L2)
* content.url insert OblCreator(#SHOULD:able-to-populate,L2)
* content.title insert OblCreator(#SHOULD:able-to-populate,L2)
* content.creation insert OblCreator(#SHOULD:populate-if-known,L2)
* content.hash insert OblCreator(#SHOULD:populate-if-known,L2)
* content.size insert OblCreator(#SHOULD:populate-if-known,L2)

* height insert OblCreator(#SHALL:populate-if-known,L3)
* width insert OblCreator(#SHALL:populate-if-known,L3)
* frames insert OblCreator(#SHALL:populate-if-known,L3)
* duration insert OblCreator(#SHALL:populate-if-known,L3)
* bodySite insert OblCreator(#SHALL:populate-if-known,L3)
* content.contentType insert OblCreator(#SHALL:able-to-populate,L3)
* content.language insert OblCreator(#SHALL:able-to-populate,L3)
* content.data insert OblCreator(#SHALL:able-to-populate,L3)
* content.url insert OblCreator(#SHALL:able-to-populate,L3)
* content.title insert OblCreator(#SHALL:able-to-populate,L3)
* content.creation insert OblCreator(#SHALL:populate-if-known,L3)
* content.hash insert OblCreator(#SHALL:populate-if-known,L3)
* content.size insert OblCreator(#SHALL:populate-if-known,L3)

* height insert OblConsumer(#SHOULD:display,L2)
* width insert OblConsumer(#SHOULD:display,L2)
* frames insert OblConsumer(#SHOULD:display,L2)
* duration insert OblConsumer(#SHOULD:display,L2)
* bodySite insert OblConsumer(#SHOULD:display,L2)
* content.contentType insert OblConsumer(#SHOULD:display,L2)
* content.language insert OblConsumer(#SHOULD:display,L2)
* content.data insert OblConsumer(#SHOULD:display,L2)
* content.url insert OblConsumer(#SHOULD:display,L2)
* content.title insert OblConsumer(#SHOULD:display,L2)
* content.creation insert OblConsumer(#SHOULD:display,L2)
* content.hash insert OblConsumer(#SHOULD:display,L2)
* content.size insert OblConsumer(#SHOULD:display,L2)

* height insert OblConsumer(#SHALL:display,L3)
* width insert OblConsumer(#SHALL:display,L3)
* frames insert OblConsumer(#SHALL:display,L3)
* duration insert OblConsumer(#SHALL:display,L3)
* bodySite insert OblConsumer(#SHALL:display,L3)
* content.contentType insert OblConsumer(#SHALL:display,L3)
* content.language insert OblConsumer(#SHALL:display,L3)
* content.data insert OblConsumer(#SHALL:display,L3)
* content.url insert OblConsumer(#SHALL:display,L3)
* content.title insert OblConsumer(#SHALL:display,L3)
* content.creation insert OblConsumer(#SHALL:display,L3)
* content.hash insert OblConsumer(#SHALL:display,L3)
* content.size insert OblConsumer(#SHALL:display,L3)
