Profile: CZ_ObservationResultObligationsImg
Parent: CZ_ObservationResultImaging
Id: cz-observationResult-obl-img
Title:    "ObservationResult: Obligations"
Description: "This profile defines obligations for an observation result in FHIR for the purpose of this guide."
// * ^publisher = "HL7 Europe"
// * ^copyright = "HL7 Europe"
* insert SetFmmandStatusRule ( 0, informative)

* note insert OblCreator(#SHOULD:able-to-populate,L2)
* hasMember insert OblCreator(#SHOULD:able-to-populate,L2)
* component insert OblCreator(#SHOULD:able-to-populate,L2)
* specimen insert OblCreator(#SHOULD:able-to-populate,L2)
* referenceRange insert OblCreator(#SHOULD:able-to-populate,L2)
* valueQuantity insert OblCreator(#SHOULD:able-to-populate,L2)
* valueString insert OblCreator(#SHOULD:able-to-populate,L2)
* valueCodeableConcept insert OblCreator(#SHOULD:able-to-populate,L2)
* interpretation insert OblCreator(#SHOULD:able-to-populate,L2)
* method insert OblCreator(#SHOULD:able-to-populate,L2)
* derivedFrom insert OblCreator(#SHOULD:able-to-populate,L2)
* bodySite insert OblCreator(#SHOULD:able-to-populate,L2)
* status insert OblCreator(#SHOULD:able-to-populate,L2)
* code insert OblCreator(#SHOULD:able-to-populate,L2)
* category insert OblCreator(#SHOULD:able-to-populate,L2)
* device insert OblCreator(#SHOULD:able-to-populate,L2)
* effectiveDateTime insert OblCreator(#SHOULD:populate-if-known,L2)

* note insert OblCreator(#SHALL:able-to-populate,L3)
* hasMember insert OblCreator(#SHALL:able-to-populate,L3)
* component insert OblCreator(#SHALL:able-to-populate,L3)
* specimen insert OblCreator(#SHALL:able-to-populate,L3)
* referenceRange insert OblCreator(#SHALL:able-to-populate,L3)
* valueQuantity insert OblCreator(#SHALL:able-to-populate,L3)
* valueString insert OblCreator(#SHALL:able-to-populate,L3)
* valueCodeableConcept insert OblCreator(#SHALL:able-to-populate,L3)
* interpretation insert OblCreator(#SHALL:able-to-populate,L3)
* method insert OblCreator(#SHALL:able-to-populate,L3)
* derivedFrom insert OblCreator(#SHALL:able-to-populate,L3)
* bodySite insert OblCreator(#SHALL:able-to-populate,L3)
* status insert OblCreator(#SHALL:able-to-populate,L3)
* code insert OblCreator(#SHALL:able-to-populate,L3)
* category insert OblCreator(#SHALL:able-to-populate,L3)
* device insert OblCreator(#SHALL:able-to-populate,L3)
* effectiveDateTime insert OblCreator(#SHALL:populate-if-known,L3)

* note insert OblConsumer(#SHOULD:display,L2)
* hasMember insert OblConsumer(#SHOULD:display,L2)
* component insert OblConsumer(#SHOULD:display,L2)
* specimen insert OblConsumer(#SHOULD:display,L2)
* referenceRange insert OblConsumer(#SHOULD:display,L2)
* valueQuantity insert OblConsumer(#SHOULD:display,L2)
* valueString insert OblConsumer(#SHOULD:display,L2)
* valueCodeableConcept insert OblConsumer(#SHOULD:display,L2)
* interpretation insert OblConsumer(#SHOULD:display,L2)
* method insert OblConsumer(#SHOULD:display,L2)
* derivedFrom insert OblConsumer(#SHOULD:display,L2)
* bodySite insert OblConsumer(#SHOULD:display,L2)
* status insert OblConsumer(#SHOULD:display,L2)
* code insert OblConsumer(#SHOULD:display,L2)
* category insert OblConsumer(#SHOULD:display,L2)
* device insert OblConsumer(#SHOULD:display,L2)
* effectiveDateTime insert OblConsumer(#SHOULD:display,L2)

* note insert OblConsumer(#SHALL:display,L3)
* hasMember insert OblConsumer(#SHALL:display,L3)
* component insert OblConsumer(#SHALL:display,L3)
* specimen insert OblConsumer(#SHALL:display,L3)
* referenceRange insert OblConsumer(#SHALL:display,L3)
* valueQuantity insert OblConsumer(#SHALL:display,L3)
* valueString insert OblConsumer(#SHALL:display,L3)
* valueCodeableConcept insert OblConsumer(#SHALL:display,L3)
* interpretation insert OblConsumer(#SHALL:display,L3)
* method insert OblConsumer(#SHALL:display,L3)
* derivedFrom insert OblConsumer(#SHALL:display,L3)
* bodySite insert OblConsumer(#SHALL:display,L3)
* status insert OblConsumer(#SHALL:display,L3)
* code insert OblConsumer(#SHALL:display,L3)
* category insert OblConsumer(#SHALL:display,L3)
* device insert OblConsumer(#SHALL:display,L3)
* effectiveDateTime insert OblConsumer(#SHALL:display,L3)
