Profile: CZ_StudyImagingObligationsImg
Parent: CZ_StudyImaging
Id: cz-studyImaging-obl-img
Title:    "Study Imaging: Obligations"
Description: "This profile defines obligations for a study imaging in FHIR for the purpose of this guide."
// * ^publisher = "HL7 Europe"
// * ^copyright = "HL7 Europe"


* modality insert OblCreator(#SHALL:able-to-populate,L2)
* series.bodySite insert OblCreator(#SHALL:able-to-populate,L2)
* identifier insert OblCreator(#SHOULD:able-to-populate,L2)
* numberOfSeries insert OblCreator(#SHOULD:able-to-populate,L2)
* numberOfInstances insert OblCreator(#SHOULD:able-to-populate,L2)
* subject insert OblCreator(#SHALL:able-to-populate,L2)
* basedOn insert OblCreator(#SHOULD:able-to-populate,L2)
* procedureCode insert OblCreator(#SHOULD:populate-if-known,L2)
* series.performer insert OblCreator(#SHOULD:populate-if-known,L2)
* series.number insert OblCreator(#SHOULD:able-to-populate,L2)
* series.description insert OblCreator(#SHOULD:populate-if-known,L2)
* description insert OblCreator(#SHOULD:populate-if-known,L2)
* reasonCode insert OblCreator(#SHOULD:populate-if-known,L2)
* note insert OblCreator(#SHOULD:populate-if-known,L2)
* endpoint insert OblCreator(#SHOULD:populate-if-known,L2)
* status insert OblCreator(#SHALL:able-to-populate,L2)
* basedOn[orderaccession] insert OblCreator(#SHALL:able-to-populate,L2)
* started insert OblCreator(#SHOULD:populate-if-known,L2)

* modality insert OblCreator(#SHALL:able-to-populate,L3)
* series.bodySite insert OblCreator(#SHALL:able-to-populate,L3)
* identifier insert OblCreator(#SHOULD:able-to-populate,L3)
* numberOfSeries insert OblCreator(#SHOULD:able-to-populate,L3)
* numberOfInstances insert OblCreator(#SHOULD:able-to-populate,L3)
* subject insert OblCreator(#SHALL:able-to-populate,L3)
* basedOn insert OblCreator(#SHOULD:able-to-populate,L3)
* procedureCode insert OblCreator(#SHOULD:populate-if-known,L3)
* series.performer insert OblCreator(#SHOULD:populate-if-known,L3)
* series.number insert OblCreator(#SHOULD:able-to-populate,L3)
* series.description insert OblCreator(#SHOULD:populate-if-known,L3)
* description insert OblCreator(#SHOULD:populate-if-known,L3)
* reasonCode insert OblCreator(#SHOULD:populate-if-known,L3)
* note insert OblCreator(#SHOULD:populate-if-known,L3)
* endpoint insert OblCreator(#SHOULD:populate-if-known,L3)
* status insert OblCreator(#SHALL:able-to-populate,L3)
* basedOn[orderaccession] insert OblCreator(#SHALL:able-to-populate,L3)
* started insert OblCreator(#SHOULD:populate-if-known,L3)

* modality insert OblConsumer(#SHALL:display,L2)
* series.bodySite insert OblConsumer(#SHALL:display,L2)
* identifier insert OblConsumer(#SHOULD:display,L2)
* numberOfSeries insert OblConsumer(#SHOULD:display,L2)
* numberOfInstances insert OblConsumer(#SHOULD:display,L2)
* subject insert OblConsumer(#SHALL:display,L2)
* basedOn insert OblConsumer(#SHOULD:display,L2)
* procedureCode insert OblConsumer(#SHOULD:display,L2)
* series.performer insert OblConsumer(#SHOULD:display,L2)
* series.number insert OblConsumer(#SHOULD:display,L2)
* series.description insert OblConsumer(#SHOULD:display,L2)
* description insert OblConsumer(#SHOULD:display,L2)
* reasonCode insert OblConsumer(#SHOULD:display,L2)
* note insert OblConsumer(#SHOULD:display,L2)
* endpoint insert OblConsumer(#SHOULD:display,L2)
* status insert OblConsumer(#SHALL:display,L2)
* basedOn[orderaccession] insert OblConsumer(#SHALL:display,L2)
* started insert OblConsumer(#SHOULD:display,L2)

* modality insert OblConsumer(#SHALL:display,L3)
* series.bodySite insert OblConsumer(#SHALL:display,L3)
* identifier insert OblConsumer(#SHOULD:display,L3)
* numberOfSeries insert OblConsumer(#SHOULD:display,L3)
* numberOfInstances insert OblConsumer(#SHOULD:display,L3)
* subject insert OblConsumer(#SHALL:display,L3)
* basedOn insert OblConsumer(#SHOULD:display,L3)
* procedureCode insert OblConsumer(#SHOULD:display,L3)
* series.performer insert OblConsumer(#SHOULD:display,L3)
* series.number insert OblConsumer(#SHOULD:display,L3)
* series.description insert OblConsumer(#SHOULD:display,L3)
* description insert OblConsumer(#SHOULD:display,L3)
* reasonCode insert OblConsumer(#SHOULD:display,L3)
* note insert OblConsumer(#SHOULD:display,L3)
* endpoint insert OblConsumer(#SHOULD:display,L3)
* status insert OblConsumer(#SHALL:display,L3)
* basedOn[orderaccession] insert OblConsumer(#SHALL:display,L3)
* started insert OblConsumer(#SHOULD:display,L3)